name: flutter_application_1
description: "CareMatch - Find the right caregiver for your needs"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10
  http: ^1.2.0
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  file_picker: 10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quattrocento Sans
      fonts:
        - asset: assets/fonts/QuattrocentoSans-Regular.ttf
        - asset: assets/fonts/QuattrocentoSans-Bold.ttf
          weight: 700
